name: Ruby 3

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 3
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.x.x
    - name: Build and test with Rake
      run: |
        sudo apt-get install libsqlite3-dev
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
